version: '3.0'

services:
  app:
    container_name: app-container
    environment:
      - POSTGRES_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
    build: ./
    networks:
      - db-app-network
    ports:
      - ${PORT}:4000
    restart: always
    volumes:
      - ./src:/app/src
    depends_on:
      - db

  db:
    container_name: db-container
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    build: ./db
    networks:
      - db-app-network
    ports:
      - ${POSTGRES_PORT}:5432
    restart: always
    volumes:
      - ./db/data:/var/lib/postgresql/data
    command: postgres -c logging_collector=on

networks:
  db-app-network:
    driver: bridge
